/**
 * proofSizeLimits.test.ts — Issue #830
 *
 * Covers proof-size boundary conditions and large-batch behaviour for the
 * Merkle reward distributor:
 *
 * 1. Proof depth is bounded by ⌈log₂(N)⌉ for a tree of N entries.
 * 2. validateProofSize rejects arrays that exceed MAX_PROOF_DEPTH.
 * 3. Large reward batches (up to MAX_BATCH_ENTRIES) produce correct,
 *    verifiable proofs without exceeding the depth limit.
 * 4. Oversized inputs (beyond MAX_BATCH_ENTRIES) degrade safely and are
 *    explicitly flagged.
 * 5. Pagination of large entry sets yields consistent roots across pages.
 */

import {
  generateMerkleTree,
  verifyProof,
  validateProofSize,
  MAX_PROOF_DEPTH,
  MAX_BATCH_ENTRIES,
  type RewardEntry,
} from "../merkleTree";

// ── Helpers ──────────────────────────────────────────────────────────────────

function makeEntries(count: number): RewardEntry[] {
  return Array.from({ length: count }, (_, i) => ({
    index: i,
    address: `GADDR${i.toString().padStart(6, "0")}`,
    amount: ((i + 1) * 1000).toString(),
  }));
}

// ── 1. Proof depth is bounded by ⌈log₂(N)⌉ ──────────────────────────────────

describe("proof depth boundary", () => {
  const cases: Array<{ n: number; maxDepth: number }> = [
    { n: 1, maxDepth: 0 },    // single leaf — no siblings needed
    { n: 2, maxDepth: 1 },
    { n: 4, maxDepth: 2 },
    { n: 8, maxDepth: 3 },
    { n: 16, maxDepth: 4 },
    { n: 32, maxDepth: 5 },
    { n: 64, maxDepth: 6 },
    { n: 128, maxDepth: 7 },
    { n: 256, maxDepth: 8 },
    { n: 512, maxDepth: 9 },
    { n: 1000, maxDepth: 10 },
    { n: 1024, maxDepth: 10 },
  ];

  for (const { n, maxDepth } of cases) {
    it(`tree of ${n} entries: all proof depths ≤ ${maxDepth}`, () => {
      const entries = makeEntries(n);
      const { claims } = generateMerkleTree(entries);

      for (const claim of Object.values(claims)) {
        expect(claim.proof.length).toBeLessThanOrEqual(maxDepth);
      }
    });
  }

  it("proof depth never exceeds MAX_PROOF_DEPTH for a tree of MAX_BATCH_ENTRIES", () => {
    const entries = makeEntries(MAX_BATCH_ENTRIES);
    const { claims } = generateMerkleTree(entries);

    for (const claim of Object.values(claims)) {
      expect(claim.proof.length).toBeLessThanOrEqual(MAX_PROOF_DEPTH);
    }
  });
});

// ── 2. validateProofSize ──────────────────────────────────────────────────────

describe("validateProofSize", () => {
  it("accepts an empty proof (single-leaf tree)", () => {
    const result = validateProofSize([]);
    expect(result.valid).toBe(true);
    expect(result.reason).toBeUndefined();
  });

  it("accepts a proof exactly at MAX_PROOF_DEPTH", () => {
    const proof = Array.from({ length: MAX_PROOF_DEPTH }, () => "a".repeat(64));
    const result = validateProofSize(proof);
    expect(result.valid).toBe(true);
  });

  it("rejects a proof one element over MAX_PROOF_DEPTH", () => {
    const proof = Array.from({ length: MAX_PROOF_DEPTH + 1 }, () => "b".repeat(64));
    const result = validateProofSize(proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toMatch(/exceeds maximum/i);
    expect(result.reason).toContain(String(MAX_PROOF_DEPTH + 1));
  });

  it("rejects a heavily oversized proof (e.g. 64 elements)", () => {
    const proof = Array.from({ length: 64 }, () => "c".repeat(64));
    const result = validateProofSize(proof);
    expect(result.valid).toBe(false);
  });

  it("accepts proofs generated by trees up to MAX_BATCH_ENTRIES", () => {
    const entries = makeEntries(MAX_BATCH_ENTRIES);
    const { claims } = generateMerkleTree(entries);

    for (const claim of Object.values(claims)) {
      const result = validateProofSize(claim.proof);
      expect(result.valid).toBe(true);
    }
  });
});

// ── 3. Large batch correctness ────────────────────────────────────────────────

describe("large reward batch correctness", () => {
  const largeBatchSizes = [500, 1_000, 5_000, MAX_BATCH_ENTRIES];

  for (const batchSize of largeBatchSizes) {
    it(`all proofs valid for ${batchSize} recipients`, () => {
      const entries = makeEntries(batchSize);
      const { root, claims } = generateMerkleTree(entries);

      // Spot-check first, middle, and last entries
      const spots = [
        entries[0],
        entries[Math.floor(batchSize / 2)],
        entries[batchSize - 1],
      ];

      for (const entry of spots) {
        const claim = claims[entry.address];
        expect(claim).toBeDefined();
        expect(verifyProof(root, claim.index, entry.address, claim.amount, claim.proof)).toBe(true);
      }
    });
  }

  it("root is deterministic across identical large batches", () => {
    const entries = makeEntries(2_000);
    const { root: root1 } = generateMerkleTree(entries);
    const { root: root2 } = generateMerkleTree(entries);
    expect(root1).toBe(root2);
  });

  it("roots differ for batches of different sizes", () => {
    const { root: small } = generateMerkleTree(makeEntries(100));
    const { root: large } = generateMerkleTree(makeEntries(200));
    expect(small).not.toBe(large);
  });
});

// ── 4. Safe degradation for oversized inputs ──────────────────────────────────

describe("oversized input safe degradation", () => {
  it("entries exceeding MAX_BATCH_ENTRIES still produce a valid tree (graceful)", () => {
    // The current implementation does not hard-reject oversized batches at the
    // tree-generation layer — callers are responsible for enforcing MAX_BATCH_ENTRIES.
    // This test documents the safe lower-bound: even if a caller passes more entries
    // the tree remains internally consistent and all proofs still verify.
    const oversize = MAX_BATCH_ENTRIES + 1;
    const entries = makeEntries(oversize);
    const { root, claims } = generateMerkleTree(entries);

    expect(root).toHaveLength(64);
    expect(Object.keys(claims)).toHaveLength(oversize);

    // First and last entries must still verify
    const first = entries[0];
    const last = entries[oversize - 1];
    expect(verifyProof(root, claims[first.address].index, first.address, first.amount, claims[first.address].proof)).toBe(true);
    expect(verifyProof(root, claims[last.address].index, last.address, last.amount, claims[last.address].proof)).toBe(true);
  });

  it("a tampered oversized proof is correctly rejected by verifyProof", () => {
    const entries = makeEntries(512);
    const { root, claims } = generateMerkleTree(entries);
    const target = entries[0];
    const claim = claims[target.address];

    // Pad the proof beyond MAX_PROOF_DEPTH with junk hashes
    const bloatedProof = [...claim.proof, ...Array.from({ length: MAX_PROOF_DEPTH }, () => "f".repeat(64))];

    expect(validateProofSize(bloatedProof).valid).toBe(false);
    // verifyProof will also fail since the computed hash won't match the root
    expect(verifyProof(root, claim.index, target.address, claim.amount, bloatedProof)).toBe(false);
  });

  it("modifying a proof element invalidates the claim", () => {
    const entries = makeEntries(16);
    const { root, claims } = generateMerkleTree(entries);
    const entry = entries[4];
    const claim = claims[entry.address];

    const corruptedProof = [...claim.proof];
    if (corruptedProof.length > 0) {
      corruptedProof[0] = "0".repeat(64);
    }

    expect(verifyProof(root, claim.index, entry.address, claim.amount, corruptedProof)).toBe(false);
  });
});

// ── 5. Pagination of large entry sets ────────────────────────────────────────

describe("paginated distribution consistency", () => {
  it("combining two page slices into one batch yields the same root", () => {
    const allEntries = makeEntries(200);
    const page1 = allEntries.slice(0, 100);
    const page2 = allEntries.slice(100, 200);

    // A full distribution is computed over all entries, not per-page
    const { root: fullRoot, claims: fullClaims } = generateMerkleTree(allEntries);

    // Re-index page1 and page2 as independent slices should produce DIFFERENT roots
    const { root: partialRoot1 } = generateMerkleTree(page1);
    const { root: partialRoot2 } = generateMerkleTree(page2);

    expect(partialRoot1).not.toBe(fullRoot);
    expect(partialRoot2).not.toBe(fullRoot);

    // But the full tree proofs still verify against the full root
    for (const entry of allEntries) {
      const claim = fullClaims[entry.address];
      expect(verifyProof(fullRoot, claim.index, entry.address, claim.amount, claim.proof)).toBe(true);
    }
  });

  it("generating a tree over a subset produces a proof that fails on the full root", () => {
    const allEntries = makeEntries(50);
    const subset = allEntries.slice(0, 25);

    const { root: fullRoot } = generateMerkleTree(allEntries);
    const { root: subRoot, claims: subClaims } = generateMerkleTree(subset);

    // Proofs from the subset tree are only valid against the subset root
    const entry = subset[0];
    const claim = subClaims[entry.address];
    expect(verifyProof(subRoot, claim.index, entry.address, claim.amount, claim.proof)).toBe(true);
    expect(verifyProof(fullRoot, claim.index, entry.address, claim.amount, claim.proof)).toBe(false);
  });

  it("proof depths grow logarithmically as batch size doubles", () => {
    const depths: number[] = [];
    let n = 1;
    for (let step = 0; step < 12; step++) {
      const entries = makeEntries(n);
      const { claims } = generateMerkleTree(entries);
      const sample = Object.values(claims)[0];
      depths.push(sample.proof.length);
      n *= 2;
    }

    // Each doubling adds at most 1 to the maximum proof depth
    for (let i = 1; i < depths.length; i++) {
      expect(depths[i]).toBeLessThanOrEqual(depths[i - 1] + 1);
    }
  });
});
